version: "3.8"

# volumes:
#   rabbitmq_data:

services:

  ###################################
  # Report: The Report microservice
  ###################################
  report:
    build:
      context: ./
      dockerfile: Dockerfile
    image: bioxmech/report:ecp
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/report
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"